import { useColorModeValue } from '@chakra-ui/color-mode';
import type { NextPage } from 'next';
import Head from 'next/head';
import NavBar from '../components/layout/navbar';
import styles from '../styles/Home.module.css';
import useTranslation from 'next-translate/useTranslation';

const Home: NextPage = () => {
  const background = useColorModeValue('#ecf2f7', '#2c303d');
  const { t } = useTranslation('index');

  return (
    <div className={styles.container}>
      <Head>
        <title>NFT Boats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <NavBar />
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">NFT Boats!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code} style={{ background }}>
            pages/index.tsx
          </code>
        </p>
      </main>
    </div>
  );
};

export default Home;
