import type { NextPage } from 'next';
import Head from 'next/head';
import NavBar from '../components/layout/navbar';
import useTranslation from 'next-translate/useTranslation';
import { Flex } from '@chakra-ui/layout';

const Home: NextPage = () => {
  const { t } = useTranslation('index');

  return (
    <>
      <Head>
        <title>NFT Boats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction="column">
        <NavBar />
        <p>{t('switch_theme')}</p>
      </Flex>
    </>
  );
};

export default Home;
