import type { NextPage } from 'next';
import Head from 'next/head';
import NavBar from '../components/layout/navbar';
import { Box, Flex, Grid, Heading } from '@chakra-ui/layout';
import Card from '../components/nft/Card';
import { motion } from 'framer-motion';
import useTranslation from 'next-translate/useTranslation';

const MotionGrid = motion(Grid);

const list = {
  show: {
    opacity: 1,
    y: 0,
    transition: {
      staggerChildren: 0.1,
    },
  },
  hidden: {
    opacity: 0,
    y: 10,
  },
};

const Home: NextPage = () => {
  const { t } = useTranslation('index');

  return (
    <>
      <Head>
        <title>NFT Boats</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex direction="column">
        <NavBar />
        <Box p={10}>
          <Heading pb={5}>{t('boat_list')}</Heading>
          <MotionGrid
            justifyContent="left"
            autoFlow="column"
            gap={10}
            variants={list}
            initial="hidden"
            animate="show"
          >
            <Card name="Boat #1" image="/assets/images/01.png" price={0.25} popular={true} />
            <Card name="Boat #2" image="/assets/images/02.png" price={0.5} popular={true} />
            <Card name="Boat #3" image="/assets/images/03.png" price={1.25} popular={false} />
            <Card name="Boat #4" image="/assets/images/04.png" price={2.1} popular={false} />
          </MotionGrid>
        </Box>
      </Flex>
    </>
  );
};

export default Home;
